[package]
name = "aup3conv"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.5.0"
rusqlite = { version = "0.31.0", features = ["blob"] }
wav = "1.0.0"
