[package]
name = "aup3conv"
version = "0.1.1"
edition = "2021"

[lib]
name = "_aup3conv"
crate-type = ["cdylib"]

[dependencies]
byteorder = "1.5.0"
rusqlite = { version = "0.31.0", features = ["blob", "bundled"] }
pyo3 = { version = "0.21.2", features = ["extension-module"] }
